language: node_js
node_js: stable
install:
- npm install
script:
- hexo cl
- hexo g
- hexo d
after_script:
- cd ./public
- git init
- git config user.name "gsherofly007"
- git config user.email "gsherofly@qq.com"
- git add .
- git commit -m "update"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
branches:
  only:
  - dev
env:
  global:
  - GH_REF: github.com/gsherofly007/blog.git
  - secure: WEY3yYJA+mxpKt7nYZFGr2Bi5cVTApR1UAdkGb4oOifp1ocsk0RLls1FMLPvhG3/aKLWgVwAYkDo8whiVVkgrcrr0s4L4MLiM4Os+KAEs/QAuyeFIX6G6u481HyriUhHOrDxePyBxMsh4GXIkqkU74DyY6Xbs62Epf2jffY4WEcqnrY62iYPvQ+CNfA8VATyDPM+sjzikNiEocbAILpf63uRshyuBz4YlaAcozKEbsMiNOKnwfunA0crmvFTAOnB2VavwsHDEa/frkybJLZuSTh8kdLK+h/f17hakWSAlyPavCTKCCJ82+css0jeNCoVER2tADKvEsOQ97uer0tayv7PBNuNunxpTU33Zd/U8cS6duZ8zWiORkwbMGPNjNUC3dSzgWo3zZMofkMbDUeJlIJqopYtyORWAHpcl/b+DYYgho10Qstbvgu2f4fbA/io6Cinc/yFbVWTRjhCkW1txb7vdqTgDzUKu7zafGIfBUg5/P2zay6MtIzYIlobX+nLbOqNOK5tFjCUODWM+K93bO583quZ2ntZZ93SUlbFkG7L3pQnQB84SkeGLnzBkSS4Ehu+TMrVOlQmKDoePPqZ5gAgCBBbUpzIATMe8KinFI9+LrUCEJpMagSQubf/dPL6oySMH/rgEZMJu2k+NywIGoFjYlUy4TFkudPtxSUcQnU=
