language: node_js  #设置语言

node_js: stable  #设置相应的版本

install:
  - npm install  #安装hexo及插件

script:
  - hexo cl  #清除
  - hexo g  #生成

after_script:
  - cd ./public
  - git init
  - git config user.name "gsherofly007"  #修改name
  - git config user.email "gsherofly@qq.com"  #修改email
  - git add .
  - git commit -m "update"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master  #GH_TOKEN是在Travis中配置token的名称

branches:
  only:
    - dev  #只监测hexo分支，hexo是我的分支的名称，可根据自己情况设置
env:
 global:
   - GH_REF: github.com/gsherofly007/blog.git  #设置GH_REF，注意更改yourname
   - secure: "NtaW3wcGzfxHJq1SDF0/3XoRSWSyIv/aVPUK7KKDPAi0dsmPFK89+aNWrvUc/SwXptmtbUPnWZZXKJWQnDg1KIpS+Kb4RnI98nD40JVGZpzf23qtYjPQYA5hq+qT+B+uP27WNVaE7w61lDQwHIPkPdas+mwII4FU0nc48yjIxKpvJS2UuwF9hem2xnu44OPy10YdQWOA3kBrXiRZJ7aRlWO+K9CRjZ466JFN5iisHQArmG8FNxVIbDeHtSzvGw1RN62nWhgH8Fz91lWD9f28z0ApCXJtA9DH6SJu29norNgCg4XzqVF9N/l8dRgnibs89hJ8Q2s84046sUmvr9KjR1ztPr55o2RBTnbQwGQAXtYY61aXw7+1BBOUo85rNqTxnhAkSEI2CH6SWr2kdhC2HG71L84Bfl8fjCfDgWGeJGE8Q/UWLrE4AxbaVcUoRtiBtxs4QGHdQQLGJo4PrjEElY0Rgh5bPcF3vz1zttJl8CrICcha8Y2Lq/Zbd3ptB8o+v/E/1k5oVHlXkjFD95XePCDnmtaek7r7VXFLGgrzVy9lh/zgH84yOdXX/stuzwfWDJ0xG3oMYhxO/0ZT8pJI3FWAjgIlpCJ7csLMHJxbJS7WlXDwREPcXfdd/V8jopf66WfCFMYlXIKbLbtE+/KDcaXJkfuq+AXRD+Ri2WHp/B4="
